### ISSUE TITLE
Split the large rakefile into smaller manageable ones

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-api#369]
Currently the single rakefile with about 18 task is kind of difficult to comprehend and contribute. Can this be split into multiple single task rake files?

**Comment by mosic** [comment]
Sure, that's a good idea. I'd say that the main problem is the length of some of the tasks (mainly the import ones).

**Comment by marcoherbst** [comment]
@mosic ... do you still agree this should be done, and if so, could you assign it to Junaid please, possibly with additional explanation.

**Comment by mosic** [comment]
@marcoherbst No, it's not worth spending time on. Closing.
