### ISSUE TITLE
Require Vendor / VendorModel data to be set for a camera

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-api#377]
We should require all cameras to have a set `vendor_model` data, and assume it's "other/other" if the user didn't specify it.

**Comment by marcoherbst** [comment]
You may or may not want to look at this one, or at least be aware of it, at the same time (though I suspect it's a much bigger problem: https://github.com/evercam/evercam-api/issues/483 )

**Comment by azharmalik3** [comment]
Done.
