### ISSUE TITLE
Use evercam-media for Test Camera endpoint

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-api#393]
[Test Camera endpoint](https://github.com/evercam/evercam-api/blob/260ef292423200531595cd9dd5987265fb093e8d/app/api/v1/routes/camera_routes.rb#L17-L62) is the only endpoint still talking directly to the camera, we should redirect requests to it to evercam-media server (like we do for [live snapshot endpoint](https://github.com/evercam/evercam-api/blob/afbef36c170fd5ce6f2d823962c646c7e45bb25c/app/api/v1/routes/snapshot_routes.rb#L10-L59)), so it can leverage new auth mechanisms implemented there.

**Comment by marcoherbst** [comment]
Test Camera / Snapshot is the only code left in evercam-api which talks directly to cameras, everything else is using evercam-media now. I imagine this endpoint working the same way as live/snapshot is; you'd call api.evercam.io and that would redirect to media.evercam.io with the response.
