### ISSUE TITLE
Image urls ought to be prefixed with https or with //

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-api#402]
This is for Vendor/Model endpoints, originally it was reported by @scandox in the discovery library: https://github.com/evercam/evercam-discovery-java/issues/21

> Ideally on web pages we'd load all images and thumbnails with https. Discovery currently returns images prefixed with http. It seems to me there are a few options:

> *    use a protocol relative prefix like //. Education: http://blog.wikimedia.org/2011/07/19/protocol-relative-urls-enabled-on-test-wikipedia-org/
> *    always use https. Might break Android App or other systems?
> *    we just replace the protocol when we use it in our webpages. This is easy but least correct.

**Comment by mosic** [comment]
No reason not to use https here, fixed in https://github.com/evercam/evercam-api/pull/445.
