### ISSUE TITLE
Looks like Add A Vendor / Model has many REQUIRED fields. It shouldn't. 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#409]
@shakeelanjum can you confirm this please.

**Comment by azharmalik3** [comment]
@marcoherbst  Made all unnecessary fields optional.

Now only following fields are required: `id, vendor_id, name, jpg_url, mjpg_ url, h264_url`

**Comment by azharmalik3** [comment]
@marcoherbst ok i will make mjpeg optional. And what about h264?

**Comment by marcoherbst** [comment]
also optional, in fact, jpeg should be optional too.
M


On 19 November 2015 at 09:34, Azhar Malik <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> ok i will make mjpeg
> optional. And what about h264?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/issues/409#issuecomment-158003129>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by azharmalik3** [comment]
DONE.
