### ISSUE TITLE
An API endpoint to test snapshot (or add camera) by just providing vendor (or convievably less). info

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#417]

**Comment by marcoherbst** [comment]
@shankardevy , I'd be interested in your thoughts on this. It translates obviously to evercam-media, but I think it's an interesting request from @vinnieq , @mosic may also have an opinion.

Basically it will require iterating through the unique snapshot URLs for any given vendor.

m

**Comment by mosic** [comment]
@marcoherbst If I understood correctly, this will take IP address, port and vendor id as inputs and then send a request to every known snapshot url for that vendor until it finds out which model it is?

**Comment by marcoherbst** [comment]
Bingo

**Comment by marcoherbst** [comment]
@fteem @mosic  .... you guys probably have something to say about this? It should be implemented on media ?

**Comment by fteem** [comment]
I would say yes, this should live in -media.

**Comment by marcoherbst** [comment]
This is better dealt with here:
https://github.com/evercam/evercam-media/issues/181
