### ISSUE TITLE
POST /Cameras .... external-host (IP address) should be required.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#419]
https://dash.evercam.io/swagger#!/cameras/POST_cameras_format

We have about 60 cameras in the DB with NO IP address. That's bad.

While we're at it, default ext-http to 80 if there is no value and have a quick look @ dashboard to see if you're happy with how it's validating.

Well done @shankardevy nicely spotted.

M

**Comment by azharmalik3** [comment]
Fixed.
