### ISSUE TITLE
Add camera online/offline status in response of creating camera (POST /cameras)

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-api#428]
This is the current API response for creating a camera: 

```
{
  "cameras": [
    {
      "id": "testssssssss",
      "name": "Test",
      "owned": true,
      "owner": "liutingd",
      "vendor_id": "",
      "vendor_name": "",
      "model_id": "",
      "model_name": "",
      "created_at": 1442414118,
      "updated_at": 1442414118,
      "last_polled_at": 1442414118,
      "last_online_at": 1442414118,
      "timezone": "Etc/UTC",
      "is_online": null,
      "is_public": true,
      "discoverable": false,
      "cam_username": "",
      "cam_password": "",
      "mac_address": "",
      "location": {
        "lat": 0,
        "lng": 0
      },
      "external": {
        "host": "123",
        "http": {
          "port": 11,
          "camera": "http://123:11",
          "jpg": "",
          "mjpg": ""
        },
        "rtsp": {
          "port": null,
          "mpeg": "",
          "audio": "",
          "h264": ""
        }
      },
      "internal": {
        "host": "",
        "http": {
          "port": null,
          "camera": "",
          "jpg": "",
          "mjpg": ""
        },
        "rtsp": {
          "port": null,
          "mpeg": "",
          "audio": "",
          "h264": ""
        }
      },
      "dyndns": {
        "host": "http://testssssssss.evr.cm",
        "http": {
          "jpg": "",
          "mjpg": ""
        },
        "rtsp": {
          "mpeg": "",
          "audio": "",
          "h264": ""
        }
      },
      "proxy_url": {
        "jpg": "http://evr.cm/testssssssss.jpg",
        "hls": "",
        "rtmp": ""
      },
      "rights": "snapshot,view,edit,delete,list,grant~snapshot,grant~view,grant~edit,grant~delete,grant~list",
      "thumbnail_url": ""
    }
  ]
}
```

The online status is always ```null```.  

If the camera is offline, the online status should be ```"is_online": false,```
If the camera is online, the online status should be ```"is_online": true,``` and it should has a valid thumbnail URL.

This is related to https://github.com/evercam/evercam-play-android/issues/103

**Comment by marcoherbst** [comment]
@shankardevy @mosic  , could one of you claim this issue, pls. It would be very nice to be able to differentiate between the successful & unsuccessful cameras being added.

**Comment by muneeb2542** [comment]
@mosic @marcoherbst What do you suggest should be done.Should i set the default value of "is_online" on api to true or should i set it false when a null value is submitted?

**Comment by marcoherbst** [comment]
Good question, well spotted. The ideal answer is neither, rather it should tell us the true status. I'll leave this to @mosic though to answer as there are probably complications that I don't understand.

**Comment by liutingdu** [comment]
This issue should be considered too: https://github.com/evercam/evercam-play-android/issues/133  
In order to fix that issue I did a temporary patch by forcing is_online=true when creating camera in both Android and iOS. So currently all create camera responses says camera is online, if the camera is actually offline, it will be updated when live view get's requested later. 

@mosic Is there anything new that I am not awared of?

**Comment by muneeb2542** [comment]
@marcoherbst Right now,when we create a new camera in the Dashboard, the 'is_online' field is automatically set to true and as @liutingdu explained will be updated when live view is requested later.
I think the temporary solution should be that we set it to true on API also until a new functionality is added that will deduce 'is_online' status on create.

**Comment by marcoherbst** [comment]
I could live with that, if I don't hear any better suggestions. Let's wait
until we hear from Milos ... I think he worked late last night :)
Thanks Muneeb.
M

On 21 January 2016 at 09:10, Muneeb Rana <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> Right now,when we create a
> new camera in the Dashboard, the 'is_online' field is automatically set to
> true and as @liutingdu <https://github.com/liutingdu> explained will be
> updated when live view is requested later.
> I think the temporary solution should be that we set it to true on API
> also until a new functionality is added that will deduce 'is_online' status
> on create.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/issues/428#issuecomment-173507179>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by mosic** [comment]
I agree that the most correct solution would be to check what the actual status is, but setting the default to `true` is good enough for this.

If the camera is actually offline (which should be uncommon, since the user probably tested the settings while adding the camera), it will be updated on the first snapshot request.

**Comment by liutingdu** [comment]
@mosic 

We used to check live snapshot right after camera creation, can you recall the reason why we don't do that anymore?

**Comment by mosic** [comment]
@liutingdu We did that before the code for the live/snapshot endpoint was moved from evercam-api to evercam-media and while we still used Heartbeat worker (Sidekiq) to ping cameras. We can add a call to the camera after creation to evercam-media, just create an issue there. :)

**Comment by liutingdu** [comment]
Does it have any negative effects? If it doesn't then I'll create an issue for it. Seems to me it's an improvement because currently camera always shows online in the side list until user opens live view.

And regarding to this issue(#428), it's about online/offline status in the response of adding camera, since we don't plan to test snapshot while creating the camera (because it could take a long time if the camera is offline), it's impossible to return this info in the response. Any suggestion around this?

**Comment by mosic** [comment]
It doesn't have any negative effects. I agree that it would be an improvement.

Re: this issue, I'd just return `is_online: true` as the default value - it should be true in most cases and will quickly be corrected if it's not true by the live snapshot request that's going to be added in evercam-media.

**Comment by liutingdu** [comment]
@mosic This issue is mostly related to https://github.com/evercam/evercam-play-android/issues/103, it's about adding online/offline info to the Mixpanel report for the event 'Create Camera'. Currently the report only tracks cameras are created but there is no way to know how many of them are online after creating. It seems patch online status by checking live snapshot doesn't solve this problem - because it's checked after sending the Mixpanel report..

**Comment by muneeb2542** [comment]
@liutingdu  i have made is_online 'true' for null in camera creation.This is only a temporary solution.So hopefully @mosic will updated in the near future.

**Comment by liutingdu** [comment]
It's not really a solution because we are kind of faking is_online=true and it doesn't mean anything. 

@mosic Can you confirm that currently there is no better way to achieve this ? If so I'll just close that issue..

**Comment by mosic** [comment]
@liutingdu Yes, this is the best solution at the moment. We will improve it in the future.
