### ISSUE TITLE
Sharing: What user information is given / displayed.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#437]
Camba.tv used to show the email address.

Evercam shows email addresses for non-accepted shares and then shows only the username. We made that change as we wanted to be conservative about giving out too much information about people.

We would like to switch this to much more detailed share, which includes First Name, Last Name and Avatar and Email. The problem is that right now it's hard to see who your camera is shared with.

Of course, this is not relevant for "Pending" requests. 

We'd also like to include "Shared by: ..."

+ then put this info on the dashboard.

M

**Comment by azharmalik3** [comment]
@marcoherbst show `Shared By` is not a good idea because sharer always contain camera owner ID and we already showing camera owner in share table first row.

**Comment by marcoherbst** [comment]
You're sure sharer is always camera owner?

What if marco is the owner and azhar shares with vinnie.

Then, who is the sharer ? ... It should be azhar.

If not, there's a bug.

m



On 16 October 2015 at 13:26, Azhar Malik <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> show Shared By is not a
> good idea because sharer always contain camera owner ID and we already
> showing camera owner in share table first row.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/issues/437#issuecomment-148703719>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by azharmalik3** [comment]
Yes, I am expecting sharer user instead of camera owner but it saves camera
owner ID.

I verified and it's a bug.

**Comment by marcoherbst** [comment]
Nice one.
M

On 19 October 2015 at 07:21, Azhar Malik <notifications@github.com> wrote:

> Yes, I am expecting sharer user instead of camera owner but it saves camera
> owner ID.
>
> I verified and it's a bug.
> On Oct 16, 2015 7:01 PM, "Marco Herbst" <notifications@github.com> wrote:
>
> > You're sure sharer is always camera owner?
> >
> > What if marco is the owner and azhar shares with vinnie.
> >
> > Then, who is the sharer ? ... It should be azhar.
> >
> > If not, there's a bug.
> >
> > m
> >
> >
> >
> > On 16 October 2015 at 13:26, Azhar Malik <notifications@github.com>
> wrote:
> >
> > > @marcoherbst <https://github.com/marcoherbst> show Shared By is not a
> > > good idea because sharer always contain camera owner ID and we already
> > > showing camera owner in share table first row.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > https://github.com/evercam/evercam-api/issues/437#issuecomment-148703719
> >
> > > .
> > >
> >
> >
> >
> > --
> > Marco Herbst
> > *Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
> > Mobile: +353 86 196 0451
> > Skype: marco.a.herbst
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/evercam/evercam-api/issues/437#issuecomment-148724755>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/issues/437#issuecomment-149114250>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by marcoherbst** [comment]
Good work @azharmalik3
