### ISSUE TITLE
Review the DB Schema

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#452]
![db-schema](https://cloud.githubusercontent.com/assets/5648894/10361099/cb1a0a28-6d9d-11e5-88bd-a898c0512e8c.png)

Probably not how one would design it now.

**Comment by mosic** [comment]
Note, our schema doesn't look like this currently. That's how it looked almost two years ago.

To be relevant, the graph should be regenerated after running migrations (i.e. running this script first: https://github.com/evercam/evercam-api/blob/master/scripts/create).

cc @fteem

**Comment by marcoherbst** [comment]
Tks @mosic

**Comment by fteem** [comment]
![db_diagram](https://cloud.githubusercontent.com/assets/854173/10361866/39cd7358-6dab-11e5-909f-f1999a6d423f.png)

Diagram from the current database.

/cc @mosic @marcoherbst

**Comment by marcoherbst** [comment]
![db-schema-8thoct-2](https://cloud.githubusercontent.com/assets/5648894/10362030/b3db0bb8-6da3-11e5-9efc-62397dadc6df.png)

**Comment by marcoherbst** [comment]
This doesn't seem very relevant any more.
