### ISSUE TITLE
Add links to download iOS and Android apps to bottom of shared camera emails

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#469]

**Comment by azharmalik3** [comment]
@marcoherbst what's the iOS download link?

**Comment by marcoherbst** [comment]
https://itunes.apple.com/ie/app/evercam-play-ip-camera-viewer/id983189658?mt=8

@liutingdu @vinnieq


On 29 October 2015 at 11:37, Azhar Malik <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> what's the iOS download
> link?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/issues/469#issuecomment-152154003>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by azharmalik3** [comment]
Done

**Comment by liutingdu** [comment]
@azharmalik3 

The download badge image should follow Apple & Android guidelines: 

https://developer.apple.com/app-store/marketing/guidelines/#downloadOnAppstore
http://developer.android.com/distribute/tools/promote/brand.html

What we currently have are not the right ones, could you please replace them with the ones in the guideline?

**Comment by marcoherbst** [comment]
Well spotted Ms Du :)


On 30 October 2015 at 08:47, Liuting Du <notifications@github.com> wrote:

> @azharmalik3 <https://github.com/azharmalik3>
>
> The download badge image should follow Apple & Android guidelines:
>
>
> https://developer.apple.com/app-store/marketing/guidelines/#downloadOnAppstore
> http://developer.android.com/distribute/tools/promote/brand.html
>
> What we currently have are not the right ones, could you please replace
> them with the ones in the guideline?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/issues/469#issuecomment-152462252>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst
