### ISSUE TITLE
Should we keep allowing DELETE /users/{id} deleting user's account easily?

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-api#470]
The endpoint of delete user account is publicly listed in our API doc, and all it needs are user's username, api key and id (by sending a DELETE request to ```https://api.evercam.io/v1/users/username?api_id={apiId}&api_key=apiKey```)  

Seems that everything in the user's account will be deleted easily without any further authentication, is it secure enough? I don't know much about API design, maybe we already have a backup on user data and I am just worrying too much?

**Comment by marcoherbst** [comment]
I think it's ok. API ID & KEY are equivalent in security terms to U&P . There is already a short delay between the time of requesting a delete and footage etc. actually being erased. This serves as an emergency fallback.

Meanwhile, it is on the roadmap to enable a new OAuth flow for use in the mobile apps. 

I'll close this.
