### ISSUE TITLE
Model Object Model > Add secondary stream info

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#474]
for jpeg, mjpeg and h264 we should add secondary stream info.

**Comment by azharmalik3** [comment]
@marcoherbst we already have secondary info in model object: `lowres` for jpeg and `mobile` for mp4/h264.
```"snapshots": {
          "h264": "",
          "lowres": "axis-cgi/jpg/image.cgi?resolution=cif",
          "jpg": "axis-cgi/jpg/image.cgi",
          "mpeg4": "mpeg4/media.amp",
          "mobile": "mpeg4/media.amp?resolution=QCIF",
          "mjpg": "axis-cgi/mjpg/video.cgi"
        }```

**Comment by marcoherbst** [comment]
Great, so, it's just time for some improved naming then. Thanks.

On 2 November 2015 at 08:53, Azhar Malik <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> we already have secondary
> info in model object: lowres for jpeg and mobile for mp4/h264.
> "snapshots": {
> "h264": "",
> "lowres": "axis-cgi/jpg/image.cgi?resolution=cif",
> "jpg": "axis-cgi/jpg/image.cgi",
> "mpeg4": "mpeg4/media.amp",
> "mobile": "mpeg4/media.amp?resolution=QCIF",
> "mjpg": "axis-cgi/mjpg/video.cgi"
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/issues/474#issuecomment-152959001>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by marcoherbst** [comment]
I'll close this. Model object will be rebuilt at some point.
