### ISSUE TITLE
Placeholder for DB cleanup tasks after splitting them

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#475]
@azharmalik3 @mosic , this place is for you to put your thoughts.

Ultimately, this ticket belongs to Azhar, but Milos might have some useful input.

**Comment by azharmalik3** [comment]
@marcoherbst  All constraints are removed from `snapshots` and `camera_activites` table but `evercam-media` still insert logs in `evercam-database` instead of `snapshot-database`.

**Comment by marcoherbst** [comment]
Thanks Azhar, we'll close this as it exists here  https://github.com/evercam/evercam-media/issues/134
