### ISSUE TITLE
Fix error on CameraActivity inserts

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-api#476]
This shows up in the logs as `Message: undefined method 'fullname' for nil:NilClass`, it was introduced by this commit: https://github.com/evercam/evercam-api/commit/5edb35e9128faa3fa9a0f00e445102d8e0908b83 and merged into master today in https://github.com/evercam/evercam-api/pull/392.

**Comment by mosic** [comment]
@azharmalik3  Errors that are breaking tests may be related: https://travis-ci.org/evercam/evercam-api/builds/87869261

If not, please create another issue for fixing tests.

**Comment by azharmalik3** [comment]
Fixed bug and create issue for broken tests.
