### ISSUE TITLE
Fix snapshot database setup in development

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-api#477]
Now that snapshots are in separate database the steps we use for creating the database in development and updating the schema etc. doesn't work. I fixed it just now by pointing to the same database we use for other tables. We can either just continue using this in development or update `scripts/create` etc.

**Comment by marcoherbst** [comment]
@mosic  what do you want to do with this ticket?

**Comment by mosic** [comment]
@marcoherbst We can close this, the current setup works ok, and the snapshot db will hopefully be obsolete soon.
