### ISSUE TITLE
Fix broken tests

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-api#479]
Tests broken due to multiple database functionality.

**Comment by mosic** [comment]
I fixed most of the tests in https://github.com/evercam/evercam-api/pull/490. The only tests that still aren't working are 4 tests in the log routes: [log_routes_spec.rb#L36-L81](https://github.com/evercam/evercam-api/blob/50b9bcc4b01d39f3667e9fe99232e8f32919df24/spec/app/api/v1/routes/log_routes_spec.rb#L36-L81), I marked them as pending.

**Comment by mosic** [comment]
All tests are fixed now.
