### ISSUE TITLE
Change vendor / model "other" defaults.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#481]
Currently:

 "vendor_id": "other",
 "vendor_name": "Unknown",
 "model_id": "other_default",
 "model_name": "NOT SPECIFED",

Should be: 

 "vendor_id": "other",
 "vendor_name": "Other",
 "model_id": "other_default",
 "model_name": "Other",

**Comment by muneeb2542** [comment]
@azharmalik3  is this still relevant?

**Comment by marcoherbst** [comment]
If it hasn't been done already and it is a non-breaking change, then yes.
The main thing we are fixing here is typos , it's not very significant.

**Comment by ijunaidfarooq** [comment]
its done already.
