### ISSUE TITLE
Empty rights in sharing object

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-api#484]
Endpoint : ```GET /cameras/{id}/shares```

With my account 'liutingd', camera 'hikdemo'

For some shared users I am getting:

 ```"rights": ""```

**Comment by liutingdu** [comment]
@azharmalik3 said:
>1) If camera private
Save rights [snapshot, list] for read only camera.
Save rights [Snapshot,View,Edit,List] for full rights camera.
2) If camera public
Save empty rights for read only camera.
Save rights [View,Edit] for full rights camera.
System delete camera public rights if camera is public.
rights_list.delete_if {|r| CameraRightSet::PUBLIC_RIGHTS.include?(r)} if camera.is_public?
That's it save empty camera rights.

**Comment by azharmalik3** [comment]
DONE.

**Comment by liutingdu** [comment]
@azharmalik3 Can you explain a bit about what change have you made?

**Comment by azharmalik3** [comment]
@liutingdu actually camera share did not save rights if camera is public. So, i just removed that condition.

**Comment by liutingdu** [comment]
@azharmalik3 

Can you elaborate by updating the following descriptions? I am trying to understand it as changes might need to be done in the app too.

Before:
> 1) If camera private
> Save rights [snapshot, list] for read only camera.
> Save rights [Snapshot,View,Edit,List] for full rights camera.
> 2) If camera public
> Save empty rights for read only camera.
> Save rights [View,Edit] for full rights camera.
> System delete camera public rights if camera is public.

After:
> 1) If camera private
> Save rights [snapshot, list] for read only camera.
> Save rights [Snapshot,View,Edit,List] for full rights camera.
> 2) If camera public
> {Please fill it here}

**Comment by azharmalik3** [comment]
@liutingdu do not delete rights for readonly public cameras.

**Comment by liutingdu** [comment]
Thanks for filling it in @azharmalik3 Now it's clear enough :)
