### ISSUE TITLE
CaPS sensitivity when sharing a camera with an email

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#485]
If MaRCo@evercam.io is a user and someone shares with marco@evercam.io then this invite will remain pending.  You'll see an example of this in hikdemo camera . Well spotted @vinnieq

**Comment by muneeb2542** [comment]
so should the application accept the email on such occasion or should show an invalid email address?

**Comment by marcoherbst** [comment]
it should accept it.

Marco@evercam.io is the same as marco@evercam.IO

m

On 20 November 2015 at 10:57, muneeb <notifications@github.com> wrote:

> so should the application accept the email on such occasion or should show
> an invalid email address?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/issues/485#issuecomment-158358497>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by muneeb2542** [comment]
ok
