### ISSUE TITLE
Add Hikvision mjpeg URLs to vendor-model data

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#489]
@faisal2472  ... you'll have to find those URLs. :) Not all cameras have them, the best way is to find a camera that does and then view source of the webpage.

m

**Comment by faisal2472** [comment]
I am using that source 
https://www.ispyconnect.com/man.aspx?n=Hikvision

**Comment by faisal2472** [comment]
/Streaming/channels/2/httppreview

**Comment by marcoherbst** [comment]
@faisal2472  ... a reminder.

**Comment by marcoherbst** [comment]
@faisal2472  ... another reminder !!

**Comment by marcoherbst** [comment]
@faisal2472  is this done? seems to be (mostly). If so, you can close it.

**Comment by marcoherbst** [comment]
@faisal2472  .... if this task is done, this issue should be closed. If you are confused, ask @affan00  for help.

**Comment by faisal2472** [comment]
Mjpeg URL for Hikvision cameras is /Streaming/channels/2/httppreview 
I am confused how to check which camera models have Mjpeg stream in shortest way, 
Once you teach me to access the camera and find the mjpeg feature.
![problem - copy](https://cloud.githubusercontent.com/assets/13760392/13984340/591903e0-f117-11e5-8bae-b61cd5d591ce.jpg)

What I can do for others models which are not online? Can I download technical sheet from Internet and find this model is supported Mjpeg or not.

**Comment by marcoherbst** [comment]
That's fine for now, if you've added the ones you know about, that's ok. I'll close the task and I've emailed Hikvision to get a product-feature matrix.
