### ISSUE TITLE
Fix CameraActivity development/production difference

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-api#491]
While working locally with the latest master branch I noticed that the development and production database schema differ, even after using `./scripts/create` to create a fresh database with latest migrations. The main difference is the added columns in `camera_activities` in production.

Development:
```
>> CameraActivity.columns
=> [:id, :camera_id, :access_token_id, :action, :done_at, :ip, :extra]
```
Production:
```
>> CameraActivity.columns
=> [:id, :camera_id, :access_token_id, :action, :done_at, :ip, :extra, :camera_exid, :name]
```

@azharmalik3 I'm assuming you added 2 new columns without using migrations. If not, please explain what happened here.

**Comment by mosic** [comment]
In order to fix this I removed usage of those two columns for now in https://github.com/evercam/evercam-api/commit/477568ed0de242bed9ad096d504f73c44e173549. When this is issue is fixed that can be easily reverted using `git revert 477568ed`.

**Comment by azharmalik3** [comment]
@mosic yes i added these two columns in production because i don't need migration in production level. As you know we separated database for `snapshots` and `camera_activities`. I just migrate my development database, that's why i did not add migrate file.

**Comment by azharmalik3** [comment]
@mosic added migrate file to add these two new columns and revert code to that branch.

**Comment by mosic** [comment]
@azharmalik3 Thanks for adding it now. Having migrations is still as important as before, the only thing that changed is that now we have two databases to run them on instead of one. Please keep doing it for future changes too.
