### ISSUE TITLE
There is no way to retrieve owner Email from API

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-api#493]
I got this problem while working on sharing for Android. 

In dashboard - 'Sharing' tab, it shows the owner as the first one in the list, with owner's username and Email address. The response of /sharing endpoints doesn't contains any user info, confirmed with @azharmalik3 that in dashboard, we are getting owner details directly from DB and not API.

Currently the only endpoints that returns owner info are ```GET /cameras``` and ```GET /cameras/{id}```, but it only contains owner's username, there is no way to find out owner's Email address.

In order to make it for Android / iOS, I think the easiest way is to add 'owner_email' in camera model in the response of ```GET /cameras``` and ```GET /cameras/{id}```. But it will make owner's Email address publicly visible for public cameras.

@marcoherbst @mosic @azharmalik3 Any suggestions? Maybe there are better solutions from back end point of view?

**Comment by marcoherbst** [comment]
Well done Liuting, great discovery.

I'd cc @eftimov here too as I actually think this resonates with his ACL
Access Control List conversation with Eugene.

M

On 3 November 2015 at 11:21, Liuting Du <notifications@github.com> wrote:

> I got this problem while working on sharing for Android.
>
> In dashboard - 'Sharing' tab, it shows the owner as the first one in the
> list, with owner's username and Email address. The response of /sharing
> endpoints doesn't contains any user info, confirmed with @azharmalik3
> <https://github.com/azharmalik3> that in dashboard, we are getting owner
> details directly from DB and not API.
>
> Currently the only endpoints that returns owner info are GET /cameras and GET
> /cameras/{id}, but it only contains owner's username, there is no way to
> find out owner's Email address.
>
> In order to make it for Android / iOS, I think the easiest way is to add
> 'owner_email' in camera model in the response of GET /cameras and GET
> /cameras/{id}. But it will make owner's Email address publicly visible
> for public cameras.
>
> @marcoherbst <https://github.com/marcoherbst> @mosic
> <https://github.com/mosic> @azharmalik3 <https://github.com/azharmalik3>
> Any suggestions? Maybe there are better solutions from back end point of
> view?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/issues/493>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by mosic** [comment]
@liutingdu Nicely spotted. I may be missing something, but if we need the owner email in both the Android app and the Dashboard, it makes sense to include it in the sharing endpoint? What is that email used for?

**Comment by marcoherbst** [comment]
Yes, it the sharing endpoint is probably the answer. Liuting's reluctance is that being the owner is not really the same as being a share (it's more like an ACL). Certainly your suggestion is the simplest. If no one else has an alternative opinion, we should follow @mosic suggestion.

**Comment by fteem** [comment]
@marcoherbst Thanks for cc'ing me in the convo.

I agree with Milos, adding the owner email to the sharing endpoint payload seems most straight forward. Also, does it make big difference if the owner email is included for public cameras?

**Comment by marcoherbst** [comment]
owner email public - I'm not sure, but there are some concerns there. A
user has signed up, made a camera public and we would then unknown to them,
publish their email address It just doesn't seem like a great idea.
M

On 3 November 2015 at 13:19, Ile Eftimov <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> Thanks for cc'ing me in the
> convo.
>
> I agree with Milos, adding the owner email to the sharing endpoint payload
> seems most straight forward. Also, does it make big difference if the owner
> email is included for public cameras?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/issues/493#issuecomment-153349254>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by eugenehp** [comment]
@liutingdu great catch, can you tell me please, besides sharing request, is there any other need for the owner's email in other places?

**Comment by liutingdu** [comment]
@eugenehp 

I think in ```GET /cameras/{id}/shares``` would be enough. The change doesn't need to be made to share request. My understanding is the result would be adding an extra share (which sharer and user are the same) in response of ```GET /cameras/{id}/shares``` without changing the sharing object model, and then I can tell it's the owner by checking if rights contains 'Delete' ?

**Comment by mosic** [comment]
@liutingdu That's great. Currently if a user adds a public cameras and requests `GET /cameras/{id}/shares` it gets this response back: 
```
{
"shares": []
}
```

If we keep it that way and add the owner email to only shares with higher rights, we would avoid the email being public. Would that work for the Android app?

**Comment by eugenehp** [comment]
@marcoherbst  @mosic @fteem @liutingdu this brings me back to the better understanding the Ile's Authorizer and concept of ACL on the higher level.

Besides the simple emails exchange, something like hash exchange still can be used to identify certain rights, but really, it should be designed on a higher level.

Any thoughts?

**Comment by liutingdu** [comment]
@mosic I think I am a bit confused now... What do you mean by 'shares with higher rights' ?

**Comment by marcoherbst** [comment]
just clarifying, when Milos says "a user adds a public cameras" , he means
(I think) "creates, for themself, a read-only share to a public camera".


On 3 November 2015 at 14:11, Miloš Mošić <notifications@github.com> wrote:

> @liutingdu <https://github.com/liutingdu> That's great. Currently if a
> user adds a public cameras and requests GET /cameras/{id}/shares it gets
> this response back:
>
> {
> "shares": []
> }
>
> If we keep it that way and add the owner email to only shares with higher
> rights, we would avoid the email being public. Would that work for the
> Android app?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/issues/493#issuecomment-153367046>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by mosic** [comment]
@marcoherbst Thanks for clarifying, that's exactly right.

@liutingdu I meant full-rights share in the current system. I used plural because I was thinking about future changes in this area.

**Comment by liutingdu** [comment]
@mosic Now I get it! Yes it will work.

But actually, the user has read-only rights should not be able to query  ```GET /cameras/{id}/shares``` at all, would it be more appropriate to return a 403 - Forbidden?

**Comment by mosic** [comment]
@liutingdu It may be more correct technically, but I think 403 may be weird from the user's point of view. And we would need to handle that error response in the app/dashboard etc. Returning a blank array makes more sense to me.

**Comment by liutingdu** [comment]
@mosic I am saying this because in both dashboard and the apps, the Sharing tab is always hidden if the user doesn't have full rights :)

**Comment by mosic** [comment]
@liutingdu It is hidden, but we know whether to hide it by sending a request to the shares endpoint from the backend before we render the page :)

**Comment by liutingdu** [comment]
@mosic 

In Android I check the 'rights' field in camera object returned by ```GET /cameras/{id} ``` before showing/hiding the sharing tab.

If the shares endpoint returns empty array, it's not enough to know whether the user doesn't have full rights or the camera is not shared with anyone, are you sure that's what we are doing on dashboard?

**Comment by mosic** [comment]
@liutingdu The dashboard checks the rights string too. I'm just saying that we send the request to shares endpoint in parallel, so it's easier/faster to just send the request instead of waiting for camera object and checking rights string before sending.

**Comment by marcoherbst** [comment]
@ijunaidfarooq  , liuting has an issue that depends on this . Could you tackle this next so that she can move on ? Tks.

**Comment by marcoherbst** [comment]
https://github.com/evercam/evercam-play-android/issues/116

**Comment by ijunaidfarooq** [comment]
yeah sure!

**Comment by ijunaidfarooq** [comment]
after having discussion on this with @liutingdu .. 

now in this end point  with are merging camera's owner as well after shares...

e.g
```
{
  "shares": [
    {
      "id": 18765,
      "camera_id": "gpo-cam-liuting",
      "sharer_id": "liutingd",
      "sharer_name": "liuting test",
      "sharer_email": "liuting+8@evercam.io",
      "user_id": "ldtest",
      "fullname": "Liuting Du",
      "email": "ld@evercam.io",
      "kind": "private",
      "rights": "Snapshot,View,Edit,List"
    }
 ]
    "owner":
    {
      "email": "liuting+8@evercam.io",
      "username": "liutingd",
      "fullname": "Liuting Du"
    }
}
```

with this no harm is coming towards `EvercamDash`. I have tested this locally as well.

**Comment by ijunaidfarooq** [comment]
In edition to last comment..

If a user has read only right then there will be no owner...

If user has full right then it will be owner as well.. 

@liutingdu

**Comment by liutingdu** [comment]
@ijunaidfarooq 👍 Thanks a lot

 Just checked it and it’s working as expected now. I'll make the change on Android later and will let you know if there are any further problems :)
