### ISSUE TITLE
Character ' is not allowed in firstname or lastname in POST /users

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-api#499]
Is it a known issue? Are we doing this on purpose? 

Got this problem when Ann trying to sign up with her last name  - O'Shaughnessy

**Comment by mosic** [comment]
It's not known and we aren't doing it on purpose. Good catch Liuting :+1: 

This is the regex we use for validating firstname/lastname: https://github.com/evercam/evercam-models/blob/master/lib/evercam_models/user.rb#L50-L51

And these are the the tests which try a couple different inputs: https://github.com/evercam/evercam-models/blob/master/spec/models/user_spec.rb#L108-L193

**Comment by liutingdu** [comment]
Haha I see Chinese name there :+1:

**Comment by muneeb2542** [comment]
@liutingdu character '  is now added in the models.You can use it now.
