### ISSUE TITLE
Motion Detection Fixes: Moving from Camera Object to /apps/ endpoint

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#515]
- [x] Add following (md_enabled, alert_interval_min, sensitivity, x1, y1, x2, y2, schedule, alert_email, emails) fields in motion_detection table.
- [x] Remove motion json values from camera object.
- [x] Improve existing motion detection endpoints and motion_detection  presenter class to fetch all these fields. 
- [ ] After that Shankar needs to changes his code to get motion settings from motion detection table same as cloud recordings.

@azharmalik3 , @shankardevy ... does this seem complete?

Is this handled beautifully at the DB scheme level?

M

**Comment by azharmalik3** [comment]
@marcoherbst for me this seems complete.

And i will use `schedule` same as our `cloud_recording` schedule and emails will be array like `["email1@evercam.io", "email2@evercam.io"]`.

**Comment by azharmalik3** [comment]
@marcoherbst `API` and `dashboard` changes completed.

@shankardevy last point is for you to make changes in `evercam-media`.

**Comment by marcoherbst** [comment]
@shankardevy  ... is this still a valid issue? If so, you might either do it, or create an issue for it in -media and close this one ? I'm assigning you here, hope that's correct.

**Comment by azharmalik3** [comment]
This task is completed.
