### ISSUE TITLE
Log when camera's is_public attribute is changed (and by whom)

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-api#518]

**Comment by marcoherbst** [comment]
Hmmm.... Just log each patch request.

**Comment by mosic** [comment]
We do already, but the parameters aren't logged. We can enable that and add filters for sensitive information that shouldn't end up in logs (camera password, api key).

**Comment by mosic** [comment]
This was done by me in https://github.com/evercam/evercam-api/pull/533, closing.
