### ISSUE TITLE
Add status flag for Cloud Recordings

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#522]
As per @azharmalik3 and @mosic 

There is no info in table to check whether camera is on / off / on schedule. At this time we are checking that if frequency is 1 then it's off otherwise on and if schedule is not equal fullweekcalendar then consider it on schedule. Using these conditions does not work properly on recordings tab and in admin snapshot report.

Code we are using:

if JSON.stringify(Evercam.Camera.cloud_recording.schedule) == JSON.stringify(fullWeekSchedule)
    if Evercam.Camera.cloud_recording.frequency == 1
      $("#cloud-recording-off").iCheck('check')
    else
      $("#cloud-recording-on").iCheck('check')
      showFrequencySelect()
      showDurationSelect()
  else
    $("#cloud-recording-on-scheduled").iCheck('check')

I think we should have a bit field `status (off: 0, on: 1, on_schedule: 2)`  which is used to check camera recordings off / on / on schedule.

**Comment by mosic** [comment]
Done in https://github.com/evercam/evercam-api/pull/534.
