### ISSUE TITLE
Refactor authentication helper

### ISSUE THREAD

**Issue by fteem** [evercam/evercam-api#525]
[Opening this by request from @marcoherbst.]

One concrete example that needs refactoring is this: https://github.com/evercam/evercam-api/blob/master/app/api/v1/helpers/authorization_helper.rb#L45

The whole idea of adding **this much** functionality via a mixin is error prone. I think that @mosic agrees to this as well.

P.S. Nothing urgent, we should look at this in 2016.

**Comment by marcoherbst** [comment]
@mosic is this still relevant?

**Comment by mosic** [comment]
@marcoherbst This was handled in evercam-media, closing the issue.
