### ISSUE TITLE
Remove snapshot.jpg endpoint.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#530]
Remove the endpoint

instead of /snapshot.jpg use /live/snapshot please   (with .jpg optional)

Also remove the code that redirects this.

https://github.com/evercam/evercam-api/blob/57ccd60ebe12243759ad61a638af5d2017b1e8b8/app/api/v1/routes/redirect_routes.rb

Discussed with  @mosic

**Comment by mosic** [comment]
Fixed in https://github.com/evercam/evercam-api/pull/531.
