### ISSUE TITLE
Fix user tests

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-api#543]
In the last week while the snapshots tests were broken, some changes to users snuck in that broke 12 tests. I've marked them as pending, but they should really be fixed.

**Comment by mosic** [comment]
This is the commit where I changed them, for reference: https://github.com/evercam/evercam-api/commit/9bdfc2716f1e8b74496efb68bd7aaa005f5ba31b

**Comment by azharmalik3** [comment]
Completed.
