### ISSUE TITLE
POST /cameras response with error when camera name contains colon

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-api#558]
To reproduce, just try creating a camera by sending request to endpoint ```POST /cameras```

Fill in camera name with a colon, for example ```"YCAM:DOOR"```.

I've tried some different test cases, it only works when the colon is in the end of the string.

Error response: 
(It's strange because I didn't send camera ID in my request at all)

```
Response code 400
{
  "message": "Camera ID can only contain lower case letters, numbers, hyphens and underscore. Minimum length is 4.",
  "code": "unknown_error",
  "context": [
    "id"
  ]
}
```

**Comment by marcoherbst** [comment]
This seems sensible. Is there any good reason to limit : from Camera Name ? .... If not, we should cope with it.

m

**Comment by azharmalik3** [comment]
Clean camera name before create camera-id. Fixed.

**Comment by shakeelanjum** [comment]
@azharmalik3, good, but Liuting is talking about camera NAME.

(Which returns an error about ID)

M

**Comment by azharmalik3** [comment]
@shakeelanjum reason of cleaning camera name is we are using name to create camera-id and this error occurred because use passed colon in camera name which also added in camera-id.

**Comment by liutingdu** [comment]
@azharmalik3 It's working now :+1:  And thanks for explaining the reason why it didn't work :)
