### ISSUE TITLE
Motion Detection association error.

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-api#583]
Even though a foreign key exists in the motion detection table for camera.There is no relationship listed for them in the camera model and in motion detection model it is many to one, It should be one to one.So we cannot access the motion detection settings of a camera object.

**Comment by muneeb2542** [comment]
@marcoherbst it is not that serious issue and everthing is working, previously we were accessing the motion detection settings of a camera by looking up the camera id in the md table due to association not listed we were not able to access the settings  by a camera object.So when the associations will be listed the it will be easy to access the settings.

**Comment by azharmalik3** [comment]
Association added.
