### ISSUE TITLE
User update error

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-api#584]
On updating email of user.It should be case sensitive so that whenever some one have to change from capital to small letter it does not give an error.

**Comment by muneeb2542** [comment]
@marcoherbst  it means if an email exists that has capital letters in it and person wants to just change the capital letters to small ,they should be just able to successfully update it.Right now it gives an error that the email already exists.

**Comment by marcoherbst** [comment]
You're talking about his end point presumeably:

https://dash.evercam.io/swagger#!/users/PATCH_users_id_format

?

It might be worth making that clear in the issue.

M



On 16 February 2016 at 11:00, Muneeb Rana <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> it means if an email exists
> that has capital letters in it and person wants to just change the capital
> letters to small ,they should be just able to successfully update it.Right
> now it gives an error that the email already exists.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/issues/584#issuecomment-184629478>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by muneeb2542** [comment]
yes that's the one.

**Comment by azharmalik3** [comment]
Email is saved in small case always. No need to save email case sensitive.
