### ISSUE TITLE
New endpoint: Port check

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-api#586]
I've added port check functionality in Android & iOS for adding camera and they are both using a third party API. In dashboard we are going to add this functionality too: https://github.com/evercam/evercam-dashboard/issues/686

If the third party service is down, all our clients will stop working(https://github.com/evercam/evercam-play-android/issues/145). So it's better to have our own endpoint for this. 

Something like:
```GET``` https://api.evercam.io/portcheck?ip=89.101.222.333&port=80
It should return ```true``` if the port is open and otherwise return ```false```

**Comment by mosic** [comment]
This sounds like a good idea, but I think it belongs in evercam-media, as all server <-> camera communication has been moved there. So the only difference for the apps would be calling `media.evercam.io` instead of `api.evercam.io`.

**Comment by marcoherbst** [comment]
Closing this. No real problem with it, but it belongs somewhere in 2024. Meanwhile continue to use someone else's.

**Comment by liutingdu** [comment]
I am reopening this because the port check API we currently use(http://api.predator.wtf/pcheck/?arguments=89.101.245.146&port=80) no longer works as an API endpoint. Seems it added verification  that allows browser requests only. 

@Zulqarnain-Mustafa  and I will have to update both Android and iOS client with a new third-party endpoint (We haven't found a new one yet, so it would be very helpful if anyone has a suggested third-party API)

So I still believe that we should have our own API endpoint for this, otherwise we'll have to deal with this every time the third-party API breaks. 

@mosic Do we prefer to use Ruby? Is this helpful: http://stackoverflow.com/questions/517219/ruby-see-if-a-port-is-open/517638#517638  ?

**Comment by marcoherbst** [comment]
I still don't like that we're doing this ourselves, but Milos will ask StackOverflow for some suggestions.
When we do make it , it will be /cameras/port-check unless anyone has a better idea (I dont like that name, but I'm stuck).

**Comment by marcoherbst** [comment]
Also, @liutingdu and all, you know that all endpoints are going to -media and -api is being shut down.

**Comment by mosic** [comment]
I went ahead and built this just now: https://github.com/evercam/evercam-media/pull/202

it works with IP addresses:
https://media.evercam.io/v1/cameras/port-check?address=89.101.245.146&port=80
https://media.evercam.io/v1/cameras/port-check?address=89.101.245.146&port=81

and with domains:
https://media.evercam.io/v1/cameras/port-check?address=api.evercam.io&port=443
https://media.evercam.io/v1/cameras/port-check?address=api.evercam.io&port=444

**Comment by marcoherbst** [comment]
Thanks Milos.

You could probably improve the error handling: 
https://media.evercam.io/v1/cameras/port-check?address=89.101.245.146

Or make an issue to do it later.

M

**Comment by marcoherbst** [comment]
@liutingdu @Zulqarnain-Mustafa @affan00 

This is ready for you to implement. If you need to, make the issue.
