### ISSUE TITLE
Improve error message for creating user POST /users

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-api#595]
While creating a new user using API ```POST /users```, if username contains invalid parameters, like a dot, the API response will be 
```json
{
  "message":   
     "Invalid parameters specified to request.",  
     "code": "invalid_parameters",  
     "context": [
        "username"  
  ]
}
```
Currently in Android & iOS, it will pop up this error message ```Invalid parameters specified to request.```, without giving any further information, which confuses the user.

In dashboard, it handles this by adding an additional username validation: 

<img width="595" alt="screen shot 2016-03-02 at 11 50 48" src="https://cloud.githubusercontent.com/assets/5046761/13459656/265f6db4-e06d-11e5-951a-b44640192050.png">

I could just add the same validation natively in Android, but same thing will have to be done in iOS again. And after doing this, if we make any change in the future, all the clients have to be updated seperately. 

So my proposal here is to change error message in API response to be ```"Username can consist of lower case letters then numbers, dashes & underscores"``` as a replacement of ```"Invalid parameters specified to request."```

**Comment by marcoherbst** [comment]
:+1

On 2 March 2016 at 12:00, Liuting Du <notifications@github.com> wrote:

> While creating a new user using API POST /users, if username contains
> invalid parameters, like a dot, the API response will be
>
> {
>   "message":
>      "Invalid parameters specified to request.",
>      "code": "invalid_parameters",
>      "context": [
>         "username"
>   ]
> }
>
> Currently in Android & iOS, it will pop up this error message Invalid
> parameters specified to request., without giving any further information,
> which confuses the user.
>
> In dashboard, it handles this by adding an additional username validation:
>
> [image: screen shot 2016-03-02 at 11 50 48]
> <https://cloud.githubusercontent.com/assets/5046761/13459656/265f6db4-e06d-11e5-951a-b44640192050.png>
>
> I could just add the same validation natively in Android, but same thing
> will have to be done in iOS again. And after doing this, if we make any
> change in the future, all the clients have to be updated seperately.
>
> So my proposal here is to change error message in API response to be "Username
> can consist of lower case letters then numbers, dashes & underscores" as
> a replacement of "Invalid parameters specified to request."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/issues/595>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by azharmalik3** [comment]
Fixed.

**Comment by liutingdu** [comment]
@azharmalik3 Thanks~
