### ISSUE TITLE
POST /users shouldn't allow username that contains space

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-api#596]
Now we are allowing space in API but not in dashboard. Are we doing this on purpose? 

In dashboard: 

<img width="610" alt="screen shot 2016-03-02 at 12 01 53" src="https://cloud.githubusercontent.com/assets/5046761/13459869/baf0eaa6-e06e-11e5-92fd-b81eb1e48e81.png">

But in API ```POST /users```

<img width="973" alt="screen shot 2016-03-02 at 12 02 44" src="https://cloud.githubusercontent.com/assets/5046761/13459870/baf15d74-e06e-11e5-9810-5f3c8b997f8f.png">

**Comment by azharmalik3** [comment]
Fixed.
