### ISSUE TITLE
Camera with no RTSP port shouldn't have H264 URL

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-api#608]
For ```GET /cameras``` or ```GET /cameras/id```
```
"rtsp": {
          "port": null,
          "mpeg": "",
          "audio": "",
          "h264": "rtsp://89.101.245.146/h264/ch1/main/av_stream"
        }
```

Port is null but it has an h264 URL. 

If camera has an h264 URL, the apps will try loading RTSP stream first, and switch to JPG view when it failed to load (after a few seconds). 

I could add the ```port is not null``` validation on client side but would it be better to be handled on the server? 

Let me know if I am wrong and I'll do it for the clients.

**Comment by mosic** [comment]
You're right, that looks like a bug. I'll look into it.

**Comment by mosic** [comment]
Thanks for reporting, fixed in https://github.com/evercam/evercam-api/commit/69861d9a8d9eae17f7eb9414b5c2ff602a04d98b.

**Comment by liutingdu** [comment]
@mosic 

Just realize a similar issue: Camera with no RTSP port has both HLS and RTMP URL. 

Should they be empty as well?

**Comment by mosic** [comment]
@liutingdu You're right, that's also a bug. Thanks for catching it, fixed in https://github.com/evercam/evercam-api/commit/451cc9e2fd579abc2cc07ea77d9d8ac9a25c35c7.
