### ISSUE TITLE
POST /users: Incorrect error message for username starts with a number

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-api#610]
In the API, the error message does not explain why it failed at all.
In dashboard, it's showing different message, but still doesn't make sense.

<img width="887" alt="screen shot 2016-03-24 at 12 22 17" src="https://cloud.githubusercontent.com/assets/5046761/14016907/1ffdb16a-f1bb-11e5-943b-1ac430bc2920.png">

<img width="641" alt="screen shot 2016-03-24 at 12 23 28" src="https://cloud.githubusercontent.com/assets/5046761/14016928/44507778-f1bb-11e5-9786-94f9844d2b7d.png">

**Comment by marcoherbst** [comment]
@muneeb2542 this whole thing is pretty buggy and badly built, I wonder would you look at it? from top to bottom ?

related: I just shared a camera with a non-user (by email address). He clicked on the link, filled in the form, pressed submit (maybe twice? maybe not?) and got the screen saying "error: username already exists". Meanwhile the account had been created.

Also, from the above, I see that the dash is using an error message different to the one supplied by the API. Surely that's daft? @mosic .. any reason why Muneeb should not simpilfy that?

Thanks guys, would be nice to improve this ... creating an account is something pretty important :)

M

**Comment by mosic** [comment]
@marcoherbst No reason not to simplify. I do remember that the error messages were both duplicated and messy, so there is lots of space for improvement.

**Comment by ijunaidfarooq** [comment]
@liutingdu I think there is no need to simplify the error coming from API as it is clear already.

But at dashboard LEVEL.. yes it should be displayed properly.

@marcoherbst any suggestions? 
error is already telling us that "Username can consist of lower case letters **THEN** numbers, dashes & underscores"

**Comment by marcoherbst** [comment]
@ijunaidfarooq you might have missed this recent conversation, but the dashboard should just display whatever errror is generated by the API. Always. Anywhere where this is not happening, consider it a task to fix. 

Does that answer the q?

As it happens, I see no reason to not allow a username to start with a number, do you?

Anyhow, your text is perfect, including the capital letters.

**Comment by ijunaidfarooq** [comment]
I also think there is no reason not to allow but if following the convention and getting inspiration from others then 
![Skype Usernames](https://cloud.githubusercontent.com/assets/13561999/14420067/4f83e0d6-ffe3-11e5-8d32-b0f249e1f3c8.png)
we should stick with it.. anyhow if you are willing to allow usernames to start with numbers then it can be done as well. ?? @marcoherbst

**Comment by marcoherbst** [comment]
:) Great, keep it as it is then, tks.


On 11 April 2016 at 08:46, Junaid Farooq <notifications@github.com> wrote:

> I also think there is no reason not to allow but if following the
> convention and getting inspiration from others then
> [image: Skype Usernames]
> <https://cloud.githubusercontent.com/assets/13561999/14420067/4f83e0d6-ffe3-11e5-8d32-b0f249e1f3c8.png>
> we should stick with it.. anyhow if you are willing to allow usernames to
> start with numbers then it can be done as well. ?? @marcoherbst
> <https://github.com/marcoherbst>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/issues/610#issuecomment-208208800>
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst
