### ISSUE TITLE
Additional /cameras/geojson endpoint

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#616]
An endpoint /cameras/geojson

My suggestions:
- Use the same data structure as the public geojson endpoint.
- Use the same parameters
- An additional parameter "exclude public cameras" would be helpful. (this would show me all the cameras in my account without any cameras that are public. Default = false).

If  you stumble upon a way to optionally output CSV in addition to Geojson then that would be lovely.

**Comment by marcoherbst** [comment]
Nice work @ijunaidfarooq , let's improve it:  (additional fields pls)

properties: {
marker-color: "#DC4C3F",
**Current Thumbnail Tag**: "<img width='140' src='https://media.evercam.io/v1/cameras/oil-tank/thumbnail?api_id=a2a&api_key=06a69' />",
**Current Thumbnail URL**: "https://media.evercam.io/v1/cameras/oil-tank/thumbnail?api_id=a2a&api_key=06a69'
**Camera Tag**: "<a href='http://dash.evercam.io/v1/cameras/oil-tank/live'>Oil Tank</a>",
**Camera Name**: "Oil Tank"
**Camera ID**: "oil-tank"
Data Processor: "Camba.tv Ltd 01-5383333",
**Data Controller ID**: "emeir",
Online ?: true,
Public ?: false,
Vendor/Model: "Axis Communications / M7014 QUAD VIEW",
marker-symbol: "circle"
},

**Comment by marcoherbst** [comment]
@ijunaidfarooq I think you can close this now. Nice work.

**Comment by ijunaidfarooq** [comment]
Thanks Marco..
