### ISSUE TITLE
Camera should be offline but showing online

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-api#622]
To reproduce, create a camera with incorrect password from the API with ```is_online=true``` (Android & iOS is creating camera with ```is_online=true``` because of https://github.com/evercam/evercam-play-android/issues/133)

Then the camera status stays online forever, the expected behaviour is it changes to offline after the auto snapshot check. Refreshing the live view in dashboard doesn't help.

Let me know if there are changes need to be made in the app.

**Comment by mosic** [comment]
This should be implemented in evercam-media, I made an issue just now: https://github.com/evercam/evercam-media/issues/193

**Comment by marcoherbst** [comment]
@mosic  does that mean this issue should be closed?

**Comment by mosic** [comment]
@marcoherbst Sure, closing.
