### ISSUE TITLE
ptz/presets endpoints not working

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-api#627]

**Comment by ijunaidfarooq** [comment]
Kindly provide more info on this... @muneeb2542

**Comment by muneeb2542** [comment]
The get and post for ptz/presets are not working.They were working few
hours ago but for the last hour they not working.

I have tested on bally-guile ptz, waxie dargle cam and for hik-ptz-herbst.

On 18 April 2016 at 18:36, Junaid Farooq <notifications@github.com> wrote:

> Kindly provide more info on this... @muneeb2542
> <https://github.com/muneeb2542>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/issues/627#issuecomment-211381348>
>



-- 


Muneeb-ur-Rehman
Junior Software Developer
Evercam.io

**Comment by muneeb2542** [comment]
I was using @marcoherbst 's account and all the cameras that I tested had full rights.
The endpoints that I tested are API endpoints and they still are not working.

These are the endpoints that i have tested
/cameras/{id}/ptz/presets and /cameras/{id}/ptz/presets/create/{preset_name}

**Comment by ijunaidfarooq** [comment]
You may check now.. ptz endpoints are working now...

I think this was due to SSL expiration on media.
As api send requests to media for this.. @muneeb2542
