### ISSUE TITLE
Properly Namecase existing users

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#640]
Would you mind running something like this on existing users, to clean things up a bit

https://github.com/tenderlove/namecase

Happy to not have a long term solution.

**Comment by muneeb2542** [comment]
@marcoherbst are you talking about all the users in our database or all the records of users in intercom?

**Comment by marcoherbst** [comment]
both

unless intercom is hard, in which case, just DB

On 3 June 2016 at 05:37, Muneeb Rana <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> are you talking about all
> the users in our database or all the records of users in intercom?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/evercam/evercam-api/issues/640#issuecomment-223488905>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFYx_qwr8R_J9uDutTLCPyScM87tGSd5ks5qH69-gaJpZM4Isg9t>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by muneeb2542** [comment]
@marcoherbst  I have namecased all the users on DB and intercom.

Closing this
